---

- name: Hello World
  hosts: localhost

  vars:
    greetings: "hello from playbook vars"

  vars_files:
    - "vars/demo.yml"
    - "vars/test.yml"

  tasks:
    - name: Hello World debug
      debug:
        msg: "{{greetings}}"
