---

- name: test package
  hosts: all
  become: yes

  tasks:
    - name: test yum module
      yum:
        name: git
        state: present
      when: ansible_facts['distribution'] == "CentOS"

    - name: test apt module
      apt:
        name: git
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
